### ISSUE TITLE
issue installing playsms in kali linux 

### ISSUE THREAD

**Issue by BigGod12** [playsms/playsms#650]
i got no error but /etc/ is empty
playSMS Install Script for Ubuntu (Debian based)

==================================================================
WARNING:
- This install script WILL NOT upgrade currently installed playSMS
- This install script WILL REMOVE your current playSMS database
- This install script is compatible ONLY with playSMS version 1.4
- Please BACKUP before proceeding
==================================================================

You ARE running this installation script as root
That means you need to make sure that you know what you're doing

==================================================================

Proceed ?

When you're ready press [y/Y] or press [Control+C] to cancel y

==================================================================

INSTALL DATA:

MySQL username      = playsmsuser
MySQL password      = password121
MySQL database      = playsms
MySQL host          = localhost
MySQL port          = 3306

Web server user     = www-data
Web server group    = www-data

playSMS source path = /home/smsplay/src/playSMS

playSMS web path    = /home/smsplay/public_html/playsms
playSMS lib path    = /home/smsplay/lib/playsms
playSMS bin path    = /home/smsplay/bin
playSMS log path    = /home/smsplay/log/playsms

playSMS conf path   = /etc

==================================================================

Please read and confirm INSTALL DATA above

When you're ready press [y/Y] or press [Control+C] to cancel y

==================================================================

Are you sure ?

Please read and check again the INSTALL DATA above

When you're ready press [y/Y] or press [Control+C] to cancel y

==================================================================

Installation is in progress

DO NOT press [Control+C] until this script ends

==================================================================

Getting composer from https://getcomposer.com

Please wait while the install script downloading composer

Composer is ready in this folder

Pleas wait while composer getting and updating required packages

Do not run Composer as root/super user! See https://getcomposer.org/root for details                                                                                
Continue as root/super user [yes]? no

Composer has been installed and packages has been updated

Start.................end

**Comment by TB360** [comment]
same issue in my side. could not find the reason.. 
ubuntu is in my side

**Comment by redy01** [comment]
rhel9
playsms v1.4.6
php v8.1
[11-Oct-2023 22:17:30 UTC] PHP Deprecated:  Required parameter $uid follows optional parameter $sms_receiver in /opt/playsms/public_html/plugin/core/recvsms/fn.php on line 122
[11-Oct-2023 22:17:30 UTC] PHP Deprecated:  Required parameter $select_field_name follows optional parameter $status in /opt/playsms/public_html/plugin/core/themes/fn.php on line 620
[11-Oct-2023 22:17:30 UTC] PHP Deprecated:  Required parameter $select_field_name follows optional parameter $status in /opt/playsms/public_html/plugin/core/themes/fn.php on line 731
[11-Oct-2023 22:17:30 UTC] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /opt/playsms/public_html/lib/fn_core.php:230
Stack trace:
#0 /opt/playsms/public_html/lib/fn_core.php(1009): core_call_hook()
#1 /opt/playsms/public_html/init.php(298): core_themes_get()
#2 /opt/playsms/public_html/index.php(19): include('...')
#3 {main}
  thrown in /opt/playsms/public_html/lib/fn_core.php on line 230
